### ISSUE TITLE
Stumbled across this via lobsters, how's the progress?

### ISSUE THREAD

**Issue by cellularmitosis** [kiedtl/qbe-m68k#1]
heyo,

I was thinking about trying to write a powerpc/darwin backend to QBE, and came across your [post](https://lobste.rs/s/je3o8m/qbe_notes#c_zbmobt) mentioning your m68k backend.

How far did you get?  I'll definitely be looking at your hacked 32-bit support.

**Comment by kiedtl** [comment]
Terrible -- I got burnt out after 2 months and can't stand the sight of it even now. QBE's code is pretty incomprehensible, even for a C project. It didn't help that I went in knowing next to nothing about register allocation, SSA, and so on.

As of now only very simple programs can be compiled and run (with a very weird emulator setup that I jerry-rigged and don't seem to have documented anywhere, alas). Everything in m68k/tests/funcs should be runnable, I think. There are still a lot of unfinished work to be done, especially with regalloc, which is still in a barely-functioning-but-overall-broken state.

That said m68k support is still doable. There's a small chance I might pick it up in the future.

**Comment by kiedtl** [comment]
Just realized there's a TODO file, you could take a look at that, though it does seem to be slightly out of date. Apparently many of the tests don't actually work, ahah. It's been a while...

Looking at it reminded me of the biggest area of work, turning 64-bit temporaries into pairs of 32-bit temporaries. So, in that sense, the main work of hacking 32-bit support into QBE hasn't even begun.

**Comment by cellularmitosis** [comment]
oh wow, QBE sounds pretty rough!

thanks for your perspective and the heads-up, and for the pointer at the TODO file.

hope you are having better luck with your other projects!
